apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
spec:
  replicas: {{ .Values.auditService.replicaCount }}
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      imagePullSecrets:
        - name: artifact-registry-secret
      containers:
        - name: audit-service
          image: "{{ .Values.image.repositoryAuditService }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://audit-db:5432/{{ .Values.postgres.auditDb.db }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: audit-db-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: audit-db-password
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          ports:
            - containerPort: {{ .Values.auditService.port }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.auditService.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.auditService.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.auditService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  selector:
    app: audit-service
  ports:
    - port: {{ .Values.auditService.port }}
      targetPort: {{ .Values.auditService.port }}
  type: ClusterIP

