apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-service
spec:
  replicas: {{ .Values.secretService.replicaCount }}
  selector:
    matchLabels:
      app: secret-service
  template:
    metadata:
      labels:
        app: secret-service
    spec:
      containers:
        - name: secret-service
          image: "{{ .Values.image.repositorySecretService }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://secrets-db:5432/{{ .Values.postgres.secretsDb.db }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: secrets-db-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: secrets-db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets-config
                  key: JWT_SECRET
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets-config
                  key: AES_KEY
            - name: AUDIT_SERVICE_URL
              value: http://audit-service:{{ .Values.auditService.port }}
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: {{ .Values.secretService.port }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.secretService.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.secretService.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.secretService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: secret-service
spec:
  selector:
    app: secret-service
  ports:
    - port: {{ .Values.secretService.port }}
      targetPort: {{ .Values.secretService.port }}
  type: ClusterIP

