apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  secrets-db-user: secret_user
  secrets-db-password: secret_pw
  audit-db-user: audit_user
  audit-db-password: audit_pw
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-secrets-config
type: Opaque
stringData:
  JWT_SECRET: mySuperStrongSecretKeyForJWTTokenGeneration123456
  AES_KEY: MySecure32ByteKeyForAES256Encryption!

