spring:
  application:
    name: notification-service

server:
  port: 8082

logging:
  level:
    root: INFO
    com.secrets.notification: DEBUG

gcp:
  project-id: ${GCP_PROJECT_ID:}

notifications:
  subscription-name: notifications-events-sub


